export const CodeMap = {
  FR: {currency: 'EUR',
      currencyTitle: {'RU': 'Евро',
                      'EN': 'Euro',
                      'FR':'Euro'}
      },
  CH: {currency: 'CHF',
      currencyTitle: {'RU': 'Швейцарский франк',
                      'EN': 'Swiss franc',
                      'FR':'Franc suisse'}},
  IS: {currency: 'ISK',
      currencyTitle: {'RU': 'Исландская крона',
                      'EN': 'Iceland krone',
                      'FR':'Couronne islandaise'}},
  NZ: {currency: 'NZD',
      currencyTitle: {'RU': 'Новозеландский доллар',
                      'EN': 'New Zealand dollar',
                      'FR':'Dollar néo-zélandais'}},
  NO: {currency: 'NOK',
      currencyTitle: {'RU': 'Норвежская крона',
                      'EN': 'Norwegian krone',
                      'FR':'Couronne norvégienne'}},
  TH: {currency: 'THB',
      currencyTitle: {'RU': 'Тайский бат',
                      'EN': 'Thailand bath',
                      'FR':'Baht'}},
  PH: {currency: 'PHP',
      currencyTitle: {'RU': 'Филиппинское песо',
                      'EN': 'Philippine peso',
                      'FR':'Peso philippin'}},
  HR: {currency: 'HRK',
      currencyTitle: {'RU': 'Хорватская куна',
                      'EN': 'Croatian kuna',
                      'FR':'Kuna croate'}},
  BR: {currency: 'BRL',
      currencyTitle: {'RU': 'Бразильский реал',
                      'EN': 'Brazilian Real',
                      'FR':'Réal brésilien'}},
  LK: {currency: 'LKR',
      currencyTitle: {'RU': 'Шри-ланкийская рупия',
                      'EN': 'Sri Lanka Rupee',
                      'FR':'Roupie srilankaise'}},
  JP: {currency: 'JPY',
      currencyTitle: {'RU': 'Японская иена',
                      'EN': 'Japanese yen',
                      'FR':'Yen'}}
}